targets:
  $default: #定义目标库，关键字$default默认为当前库
    builders: #构建的两个库
      lemon_lib|lemon_builder:
        options: { 'write': true }
        enabled: true #可选，是否将构建器应用于此目标
        generate_for:
          exclude: ['**.lemon.dart']

builders:
  lemon_builder:
    import: "package:lemon_lib/builder.dart" #build文件
    builder_factories: ["codeGenerator"] #build文件中对应的方法
    build_extensions: {".dart": ['.lemon.dart']}
    auto_apply: root_package #将此Builder应用于包，直接依赖于公开构建起的包
    build_to: source #输出转到隐藏的构建缓存，不会发布
